const f = ()=>{
    try{
        // let a = 0
        // console.log(ariz)
        console.log("ok hai")
        return
    }catch(err){
        console.log("this is an error")
        console.log(anas)
    }
    finally{
        console.log("I am a good boy")
        // Will always run
    }
}
f()
console.log("end")
try{
    let a = 0
    // console.log(ariz)
    console.log("ok hai")
}catch(err){
    console.log("this is an error")
    console.log(anas)
}
finally{
    console.log("I am a good boy")
}




